server :
  port: 8083
spring:
  application :
    name : RATING-SERVICE
  data:
    mongodb:
      uri : mongodb://localhost:27017/microservices

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pranjalkatyayan/My-Configration-Files-For-All-Microservices
          clone-on-start : true
          default-label: dev-branch


#Okta Configration
okta :
  oauth2:
    issuer : https://dev-45386778.okta.com/oauth2/default
    audience: api://default

