server :
  port : 8082


spring :

  application:
    name: HOTEL-SERVICE

  datasource :
    url : jdbc:mysql://localhost:3306/microservices
    username : root
    password : root



  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pranjalkatyayan/My-Configration-Files-For-All-Microservices
          clone-on-start : true
          default-label: dev-branch






